development:
  adapter: postgresql
  database: rubybot
  username: caiden
  password: caiden
  host: localhost

drop_environment:
  adapter: postgresql
  database: template1
  username: caiden
  password: caiden
  host: localhost
